export const SPANISH = {
  'Caption Styles': '字幕样式',
  'Captions look like this': '字幕示例如下',
  'Closed-Captions Off': '关闭隐藏式字幕',
  'Closed-Captions On': '开启隐藏式字幕',
  'Display Background': '显示背景',
  'Enter Fullscreen': '进入全屏',
  'Enter PiP': '进入画中画模式',
  'Exit Fullscreen': '退出全屏',
  'Exit PiP': '退出画中画',
  'Google Cast': '谷歌投屏',
  'Keyboard Animations': '键盘动画',
  'Seek Backward': '向后跳转',
  'Seek Forward': '向前跳转',
  'Skip To Live': '跳转到直播',
  'Text Background': '文字背景',
  Accessibility: '无障碍功能',
  AirPlay: '隔空播放',
  Announcements: '公告通知',
  Audio: '音频设置',
  Auto: '自动模式',
  Boost: '增强模式',
  Captions: '字幕选项',
  Chapters: '章节选择',
  Color: '颜色设置',
  Connected: '已连接',
  Connecting: '连接中',
  Continue: '继续播放',
  Default: '默认设置',
  Disabled: '已禁用',
  Disconnected: '已断开',
  Download: '下载视频',
  Family: '家庭共享',
  Font: '字体设置',
  Fullscreen: '全屏模式',
  LIVE: '直播中',
  Loop: '循环播放',
  Mute: '静音',
  Normal: '普通模式',
  Off: '关闭',
  Opacity: '透明度',
  Pause: '暂停',
  PiP: '画中画',
  Play: '播放',
  Playback: '播放控制',
  Quality: '画质选择',
  Replay: '重新播放',
  Reset: '重置设置',
  Seek: '进度跳转',
  Settings: '设置菜单',
  Shadow: '阴影效果',
  Size: '尺寸调整',
  Speed: '播放速度',
  Text: '文字设置',
  Track: '音轨选择',
  Unmute: '取消静音',
  Volume: '音量控制'
}
